{% set name = "iteration_utilities" %}
{% set version = "0.7.0" %}
{% set sha256 = "c7b53f36350515a95051eb22616e258ffe461ade31f0ba7d2cdc624de40d4718" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pytest-runner
    - pytest
  imports:
    - iteration_utilities

about:
  home: https://github.com/MSeifert04/iteration_utilities
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Utilities based on Pythons iterators and generators.'
  doc_url: https://iteration-utilities.readthedocs.io/en/stable/
  dev_url: https://github.com/MSeifert04/iteration_utilities

extra:
  recipe-maintainers:
    - MSeifert04
