{% set name = "iteration_utilities" %}
{% set version = "0.10.1" %}
{% set sha256 = "536e3e87c5c139c775f9d95bb771c4b366a1d58eb7a39436d4ac839b53742569" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - iteration_utilities

about:
  home: https://github.com/MSeifert04/iteration_utilities
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Utilities based on Pythons iterators and generators.'
  doc_url: https://iteration-utilities.readthedocs.io/en/stable/
  dev_url: https://github.com/MSeifert04/iteration_utilities

extra:
  recipe-maintainers:
    - MSeifert04
