{% set name = "iteration_utilities" %}
{% set version = "0.2.0" %}
{% set sha256 = "e32e8687f26d65930b4eb976da07392abf5b02884d7ea7aac67a60305641effc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  features:
  - vc9  # [win and py27]
  - vc10  # [win and py34]
  - vc14  # [win and py35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - pytest-runner
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - iteration_utilities

about:
  home: https://github.com/MSeifert04/iteration_utilities
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.rst
  summary: 'Utilities based on Pythons iterators and generators.'
  doc_url: http://iteration-utilities.rtfd.io
  dev_url: https://github.com/MSeifert04/iteration_utilities

extra:
  recipe-maintainers:
    - MSeifert04
