appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YcS3sYE72qgYc7oluivib38RhKpKV7AbaQCQCvGBeqNNhPaLqweg4m69GBX6maH5ZnsHc7RT+9u/KwMnG352GuRhUL2/9beA+TQZyH+hUJ9ZEf9kXJd7vqNlYFJp8lb85tA8yJVAn8bgVWOcz6/NAJKtHPFriWH7ixTxntVuZhKn72PuHGNRNAlfUTLmI3UzMlgO7X0Or9/mnnlrEpWXuJ7IMuL6Im6HOColqVw/zJXqkTBvhj2sTDJpe6LXQ0gXUko2BEDSEvdC5i8+dQz/TXC0CLBvOUkmYiRj4EtNtyn310izx50gYvzlsUXJYytVR7/W7fikUOfKIIa5gXpGsVlWRiewrxIBb33knnTFD4jYrvR5ByuKMbFOsFzUSmuytIry1SMiCAlqrTWecoeNIGqnUiXO22L66bisdEQYimUfDc3QQBpbV9myD8cVCvCu1fk60DdU0/QCcJDJEqVum0pZFjyo4se3wVJrQwb9Mxmr2LEWpe+FyCQ6khB8FHwiENKmA8Jzea4wC90rjK2JoTSSTAzzYx2+xlyT4qA3fRi8UoaZeCR9671Bb1ESDHJGQma3EbK7IFztNH39g4hA9xj2zJQVAAuG9nuJfqnIpyIpydhm64M3mWldHnO52QprUK0x1y2ABRH9auV2qR5W55MJYnmELPG+5KmnqQb5z5g=}
provider:
  win: azure
conda_forge_output_validation: true
