travis:
  secure:
    BINSTAR_TOKEN: YfFzDtHVW6mbGigkGj9cOJLB+uZLjVEqKRIsWvjlnrOtTRdr1uePDnLJJu5o2w98yUg0Purlquefj9N4hXwFUOHEV8rbK3kH5bPZxGY/e/25IJ4LZROlvc4xC25uRYrU2Wyb+sx5bBuDy1mD7Uvlj1b/dwHwu++L1MiYxD0Z0/1boVX+R1g9ZwojOFhuLbWqx95bbYdXC49YtvNRBZOP16V5lvZEftczBdtWV3eqfwxsdbSahsI7YBxianRI4K0cY8RNcsWau90mmmnDINStAkp76oFVz4xgON0vFmWnA5y4E6nLLktAGOv9hvnkPoOTZYPAwOsLd3CPvWBnDxUazgwrEMXeHIWJbWBmymgGy6XcuvUs7EVgFVxr24JOR05G9j42IZSe386vCVbwq9YDOSjpfBJkyGyZINrrwtrDyOLgiU8PLbkyyZg0sALY7ASyR2J8G+1SWO+Uz1bTXDaqKhEKF/HxPap0OStPtHYX8AARw6IP8rlzyY7rFwt73GJpyzYZzjTTPE0cdPvL40Y/hyT+2IYV0tlMmIuUoTDSWJTYnL7+nyDpwzdqLp99ghix31xq7TOOObuIBUa4O/LH/CargA8lDL4dmu7z8dM++IXbiT7qyeXr6XSlkL6rbyscZplrk3OSNJAhYlWyvYWO6ilCsXj0BteVPhY0hDVuDxM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
